from tkinter import*
piton=Tk()
piton.title('my app')
piton.geometry('250x50')
piton.configure(background='blue')
options=(1,2,3)
my_variable_objekt=IntVar()
my_variable_objekt.set('tanlang')
my_dropdown=OptionMenu(piton, my_variable_objekt, *options)
my_dropdown.grid()
my_label=Label(piton,width=40, height=5, bg='white', text=' ')
my_label.grid(row=20, column=10)
my_text_box=Entry(piton,width=40)
my_text_box.grid(row=25, column=25)
def change_text():
     my_label.config(text='mening ismim Bekmurod')
my_button=Button(piton, text="kirish", width=10, command=change_text)
my_button.grid(row=1, column=0)
my_button2=Button(piton, text="chiqish", width=10, command=change_text)
my_button2.grid(row=2, column=0)
def change_text():
    my_label.config(my_button3)
my_button3=Button(piton, text="matn kiritish", width=10, command=change_text)
my_button3.grid(row=3, column=0)
piton.mainlop()
